#1
FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o api-gateway-test

#2
FROM alpine:3.20
WORKDIR /app
COPY --from=build /app/api-gateway-test .
EXPOSE 8080
CMD ["./api-gateway-test"]