name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      plan_run_id:
        description: "Terraform Plan workflow run ID"
        required: true

env:
  AWS_REGION: eu-west-2
  TF_WORKING_DIR: terraform

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      id-token: write
      contents: read
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::985539771340:role/github-actions-terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download tfvars from S3
        run: aws s3 cp s3://ecs-microservices-config/dev/terraform.tfvars $TF_WORKING_DIR/dev.tfvars

      - name: Create Terraform plugin cache directory
        run: mkdir -p ~/.terraform.d/plugin-cache

      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('terraform/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Configure Terraform plugin cache
        run: echo 'plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Download Terraform plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          run-id: ${{ github.event.inputs.plan_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: terraform

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -input=false tfplan