name: Docker Build & Push

on:
  push:
    branches:
      - main
    paths:
      - "services/**"
      - ".github/workflows/docker.yml"  
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2
  ECR_REGISTRY: 985539771340.dkr.ecr.eu-west-2.amazonaws.com
  IMAGE_TAG: latest
  COMMIT_SHA: ${{ github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        service:
          - api-gateway
          - order-service
          - inventory-service
          - payment-service
          - notification-service
          - shipping-service
          - dashboard-api
          - worker
          - scheduler

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::985539771340:role/github-actions-terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build Docker image
        run: |
          docker build \
            -f services/${{ matrix.service }}/Dockerfile \
            -t $ECR_REGISTRY/${{ matrix.service }}:${IMAGE_TAG} \
            -t $ECR_REGISTRY/${{ matrix.service }}:${COMMIT_SHA} \
            services/${{ matrix.service }}

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/${{ matrix.service }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 0

      - name: Push Docker images
        run: |
          docker push $ECR_REGISTRY/${{ matrix.service }}:${IMAGE_TAG}
          docker push $ECR_REGISTRY/${{ matrix.service }}:${COMMIT_SHA}