name: Terraform Plan

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/plan.yml"
  #push:
   # branches:
    #  - main
    #paths:
     # - "terraform/**"
      #- ".github/workflows/plan.yml"
  workflow_run:
    workflows: ["Docker Build & Push"]
    types: [completed]

  workflow_dispatch:
    inputs:
      run_checkov:
        description: "Run Checkov scan"
        required: false
        default: "false"

env:
  AWS_REGION: eu-west-2
  TF_WORKING_DIR: terraform
  ECR_REGISTRY: 985539771340.dkr.ecr.eu-west-2.amazonaws.com
  TFVARS_S3_URI: s3://ecs-microservices-config/dev/terraform.tfvars

jobs:
  terraform-plan:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'pull_request' ||
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Show workflow context

        run: |
          echo "head_sha=${{ github.event.workflow_run.head_sha }}"
          echo "head_commit.id=${{ github.event.workflow_run.head_commit.id }}"
          echo "github.sha=${{ github.sha }}"

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::985539771340:role/github-actions-terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download tfvars from S3
        run: aws s3 cp $TFVARS_S3_URI $TF_WORKING_DIR/dev.tfvars

      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check -recursive

      - name: Create Terraform plugin cache directory
        run: mkdir -p ~/.terraform.d/plugin-cache

      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('terraform/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Configure Terraform plugin cache
        run: |
          echo 'plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Create CI overrides
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          IMAGE_TAG="${{ github.event.workflow_run.head_sha || github.sha }}"

          cat > ci.auto.tfvars <<EOF
          api_gateway_image = "${ECR_REGISTRY}/api-gateway:${IMAGE_TAG}"
          order_service_image = "${ECR_REGISTRY}/order-service:${IMAGE_TAG}"
          inventory_service_image = "${ECR_REGISTRY}/inventory-service:${IMAGE_TAG}"
          payment_service_image = "${ECR_REGISTRY}/payment-service:${IMAGE_TAG}"
          notification_service_image = "${ECR_REGISTRY}/notification-service:${IMAGE_TAG}"
          shipping_service_image = "${ECR_REGISTRY}/shipping-service:${IMAGE_TAG}"
          dashboard_api_image = "${ECR_REGISTRY}/dashboard-api:${IMAGE_TAG}"
          worker_image = "${ECR_REGISTRY}/worker:${IMAGE_TAG}"
          scheduler_image = "${ECR_REGISTRY}/scheduler:${IMAGE_TAG}"
          EOF

      - name: Show generated ci.auto.tfvars
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: cat ci.auto.tfvars
        
      - name: Install TFLint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Create TFLint plugin cache directory
        run: mkdir -p ~/.tflint.d/plugins

      - name: Cache TFLint plugins
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ runner.os }}-${{ hashFiles('**/.tflint.hcl') }}
          restore-keys: |
            tflint-${{ runner.os }}-

      - name: Run TFLint
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          tflint --init
          tflint --recursive

      - name: Install Checkov
        if: ${{ github.event.inputs.run_checkov == 'true' }}
        run: pip install checkov==3.2.450

      - name: Run Checkov
        if: ${{ github.event.inputs.run_checkov == 'true' }}
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: checkov -d . --quiet --framework terraform

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -input=false -var-file=dev.tfvars -out=tfplan

      - name: Generate human-readable plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform show -no-color tfplan > plan.txt

      - name: Upload human-readable plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-text
          path: terraform/plan.txt
          retention-days: 7

      - name: Upload Terraform plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan
          retention-days: 7